### ISSUE TITLE
cant send push 

### ISSUE THREAD

**Issue by cansuB** [cihadoge/parse-php-sdk-for-codeigniter#1]
Hi, 
I load the library and trying to send push. I dont get any error but push is not working. Any suggestions?

$push_data = array(
    'ID' => $data['siteId'],
     'alert' =>'refresh');

 $request = $this->parsepush->send(array(
"data" => $push_data
));

**Comment by cihadoge** [comment]
I think you should add channels array to your sent array like in example

```
$data = array("alert" => "Hi!");

// Push to Channels
$this->parsepush->send(array(
  "channels" => ["PHPFans"],
  "data" => $data
));

```

**Comment by cansuB** [comment]
actually I found out this is the reason of that issue 

Uncaught exception 'ParseException' with message 'SSL certificate problem: unable to get local issuer certificate'. how can I solve that?

**Comment by cihadoge** [comment]
It was common problem in parse php sdk itself, 
https://github.com/ParsePlatform/parse-php-sdk/issues/4

You can follow that topic, it also has tricky patch for that problem.

```
Add this statement to ParseClient.php before curl_exec($rest) (ParseClient.php line 246)

 curl_setopt($rest, CURLOPT_SSL_VERIFYPEER, false); 

FALSE to stop cURL from verifying the peer's certificate. Alternate certificates to verify against can be specified with the CURLOPT_CAINFO option or a certificate directory can be specified with the CURLOPT_CAPATH option.
```

**Comment by cansuB** [comment]
thanks a lot, solved it.

**Comment by cihadoge** [comment]
:+1:
